---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.operator.kcp.io
  resources:
  - compiledcacheservers
  - compiledfrontproxies
  - compiledrootshards
  - compiledshards
  - compiledvirtualworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - bundles
  - cacheservers
  - frontproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - bundles/finalizers
  - cacheservers/finalizers
  - frontproxies/finalizers
  - kubeconfigs/finalizers
  - rootshards/finalizers
  - shards/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kcp.io
  resources:
  - bundles/status
  - cacheservers/status
  - frontproxies/status
  - kubeconfigs/status
  - rootshards/status
  - shards/status
  - virtualworkspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kcp.io
  resources:
  - kubeconfigs
  - rootshards
  - shards
  - virtualworkspaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
